Spakowanie programu w mniejsze moduły.
KNR-PW/discord-bot pull request #20
Opened 2023-06-13 21:31 UTC by PiotrWeppo

Jak w tytule. Powinno polepszyć czytelność programu.

https://github.com/KNR-PW/discord-bot/issues/8

2023-06-13 22:14 UTC, pktiuk commented on main.py
> +from embed_creator import EmbedCreator, HelpMenu, auto_update
Z tego co widzę to w tym pliku są głównie widoki oraz różne elementy interfejsu.
Może lepszą nazwą byłoby coś co sugeruje, że właśnie stąd bierzemy widoki i elementy UI?
Może `bot_gui`?

2023-06-13 22:18 UTC, pktiuk requested changes
Trzeba poprawić formatowanie, aby CI się nie wywalało.  
Poza tym zalecałbym umieścić wszystkie pliki pythonowe (poza plikiem `main.py`) w folderze o nazwie `bot`. Dzięki temu nie wszystko będzie się tak walać w głównym folderze repo.
Poza tym nawet w kodzie będzie to inaczej wyglądać, bo widząc
`import bot.cośtam` od razu wiesz, że tutaj chodzi o część naszego bota, a nie jakiejś biblioteki pythonowej o nazwie `cośtam`.

Poza tym zastrzeżeń innych nie mam. Podział ma logiczny sens.

2023-06-14 16:23 UTC, PiotrWeppo commented
Hmm, mam zagwozdkę. Cały czas embed_creator i embed_methods mają błąd "circular imports". Gdybym je spakował razem to nadal moduł będzie miał poniżej 1000 wierszy (ok 750). Bardziej wolałbym przebudować kod, któregoś, ale nie wiem jak to ugryźć przy takim zaawansowaniu.

2023-06-14 16:42 UTC, PiotrWeppo commented
Próbowałem zrobić rebase przy pomocy gitgrapha, ale chyba nic z tego.

2023-06-14 19:53 UTC, pktiuk commented
> Próbowałem zrobić rebase przy pomocy gitgrapha, ale chyba nic z tego

Dziwne, u mnie działa 
![image](https://github.com/KNR-PW/discord-bot/assets/45544416/a66393ed-2690-4fa0-a180-10306fd0c811)

2023-06-14 19:54 UTC, pktiuk commented
Czemu robisz pull requesta ze swojego brancha roboczego (na własnym repo) na innego brancha roboczego (na tym repo)?

2023-06-14 20:02 UTC, pktiuk commented on main.py
> +    """A subclass of the `commands.Bot` class."""
Wcześniej przeoczyłem ten problem z komentarzami.   
Takie komentarze jak te powinny być usunięte. Chodzi tutaj o komentarze, które opisują kod 1 do 1-nego bez wnoszenia niczego od siebie. Tutaj widać że klasa dziedziczy po klasie commands.Bot, więc nie ma sensu tego komentować.

Inny przykład takiego komentarza
```py
# zwiększanie wartości numeru o 1
number = number + 1
```

2023-06-14 20:08 UTC, PiotrWeppo commented
> > Próbowałem zrobić rebase przy pomocy gitgrapha, ale chyba nic z tego
> 
> Dziwne, u mnie działa ![image](https://user-images.githubusercontent.com/45544416/245918211-a66393ed-2690-4fa0-a180-10306fd0c811.png)

Chciałem po prostu zmienić tamtego commita bez dodawania nowego. Wydaje mi się, że użyłem tej opcji i nic nie zmieniła na stronie githuba, więc zrobiłem później push branch, które z kolei zrobiło zwykłego merge'a dodając commita do historii brancha.

2023-06-14 20:09 UTC, PiotrWeppo commented
> Czemu robisz pull requesta ze swojego brancha roboczego (na własnym repo) na innego brancha roboczego (na tym repo)?

Nie rozumiem. Gdybym nie zrobił pull requesta to byś nigdy nie zauważył, że wprowadziłem jakiekolwiek zmiany. Natomiast pull requesta zrobiłem tylko raz, wczoraj. Dzisiejsze commity automatycznie się tu pojawiają, przez to, że te branche na moim originie i upstreamie są ze sobą "związane".

2023-06-14 20:10 UTC, pktiuk commented
Tu trzeba było uzyć interaktywnego rebase'a, a nie zwykłego `git rebase -i`.

2023-06-14 20:15 UTC, PiotrWeppo commented
> Tu trzeba było uzyć interaktywnego rebase'a, a nie zwykłego `git rebase -i`.

Czy można coś takiego zrobić w git graphie? Jedyne co znalazłem, to przy użyciu gitlensa:
https://www.youtube.com/watch?v=3o_01F04bZ4

2023-06-14 20:16 UTC, pktiuk commented
> Hmm, mam zagwozdkę. Cały czas embed_creator i embed_methods mają błąd "circular imports". Gdybym je spakował razem to nadal moduł będzie miał poniżej 1000 wierszy (ok 750). Bardziej wolałbym przebudować kod, któregoś, ale nie wiem jak to ugryźć przy takim zaawansowaniu.

Na ten moment połączyłbym to w jeden plik i usiadł do tego przy kolejnym pull requeście. Ogólnie jest tutaj problem z niewłaściwym podziałem. bo patrząc na wizualizację zależności klas:

![image](https://github.com/KNR-PW/discord-bot/assets/45544416/ee0d6e95-43e0-44eb-ab37-7400d2592ee7)

Widać, że do oddzielnego pliku przemieściłeś tak jakby coś co było w środku struktury, więc trzeba było przenieść klasę EmbedEditingMethods razem z klasami poniżej, albo nie przenosić wcale.

2023-06-18 15:16 UTC, PiotrWeppo commented
> Tu trzeba było uzyć interaktywnego rebase'a, a nie zwykłego `git rebase -i`.

już chyba ogarnąłem

2023-06-18 15:16 UTC, PiotrWeppo commented
> Na ten moment połączyłbym to w jeden plik i usiadł do tego przy kolejnym pull requeście. Ogólnie jest tutaj problem z niewłaściwym podziałem. bo patrząc na wizualizację zależności klas:
> 
> ![image](https://user-images.githubusercontent.com/45544416/245922731-ee0d6e95-43e0-44eb-ab37-7400d2592ee7.png)
> 
> Widać, że do oddzielnego pliku przemieściłeś tak jakby coś co było w środku struktury, więc trzeba było przenieść klasę EmbedEditingMethods razem z klasami poniżej, albo nie przenosić wcale.

Z tym sobie też poradziłem.

2023-06-18 15:42 UTC, PiotrWeppo commented
@pktiuk gotowe do review.

2023-06-19 15:34 UTC, pktiuk commented on bot/message_syntax_functions.py
> +
Mógłbyś sprawdzić, czy to jest nadal aktualne z tego co się orientuję to discord właśnie odszedł od 4-cyfrowych identyfikatorów https://discord.com/blog/usernames

2023-06-19 15:39 UTC, pktiuk commented on main.py
> +    A subclass of the `commands.Bot` class.
Komentarz przepisujący słowo w słowo to, co pokazuje kod.

2023-06-19 15:42 UTC, pktiuk requested changes
Zapomniałeś zmienić nazwę skryptu do uruchomienia w Readme. Poza tym masz jeszcze kilka niezamkniętych wątków z komentarzami

2023-06-25 14:25 UTC, PiotrWeppo commented on bot/message_syntax_functions.py
> +
Zmieniona funkcja.

2023-06-25 14:27 UTC, PiotrWeppo commented
> Zapomniałeś zmienić nazwę skryptu do uruchomienia w Readme. Poza tym masz jeszcze kilka niezamkniętych wątków z komentarzami

Mógłbyś podać przykład? Przejrzałem wszystko i z grubsza jestem zadowolony z docstringów, które stworzyłem.

2023-06-25 20:34 UTC, pktiuk approved these changes
Już wszystko wygląda git, tylko jeszcze odpalę na próbę i zmerguję

2023-06-25 20:38 UTC, merged