Changed class used to control bot from discord.Client to discord.Bot,…
KNR-PW/discord-bot pull request #7
Opened 2023-01-23 22:58 UTC by PiotrWeppo

… reduced number of functional lines of code, added a prototype of command to display server stats, added plugin to flake8 action

2023-01-26 16:54 UTC, pktiuk requested changes
Ogólnie wszystko wygląda spoko, ale trzeba ogarnąć błędy, które wskazuje ci CI

2023-01-26 18:33 UTC, PiotrWeppo commented
Dziwna sprawa, bo po mojej stronie flake8 pokazuje tylko kilka błędów z długością wiersza:
![Code_ma3ilcfQJ7](https://user-images.githubusercontent.com/117805804/214920083-ae665874-8c7e-47eb-b91d-64e0cc6df662.png)
Te błędy które są w actions, nijak się mają do tego i nie za bardzo nawet rozumiem o co mu chodzi.

2023-01-26 21:30 UTC, pktiuk commented
TO problem z akcjami, W takim wypadku na ten moment można to olać.   
To sam flake się wysypuje. Jak tak to merguję, możesz przejść do dalszych punktów

2023-01-26 21:30 UTC, merged

2023-01-26 21:31 UTC, pktiuk commented
Dobrze by było, jakbyś wrzucił tu screena pokazującego jak ten bot działa.

2023-01-26 21:49 UTC, pktiuk commented
Jak coś to wydaje mi się, że to ten plugin do flake'a wszystko psuje.  Po co dodałeś ten plugin?

2023-01-27 18:01 UTC, PiotrWeppo commented
> Dobrze by było, jakbyś wrzucił tu screena pokazującego jak ten bot działa.

Logowanie w terminalu:
![Code_LqTiDeJSoZ](https://user-images.githubusercontent.com/117805804/215160053-2e7f305d-5e05-46e3-b33c-39c75a2523f7.png)

Dostępny Bot:
![Discord_HqRWdlFaIe](https://user-images.githubusercontent.com/117805804/215160079-9fc02c95-63e1-474e-a722-bd6eb7b126e9.png)

Odpowiedź na komendę:
![Discord_q9w0gTxbt7](https://user-images.githubusercontent.com/117805804/215160149-98e1bcca-fd87-4a19-adf1-0e21d90c1503.png)

Umieszczanie tekstu. Pole "Description" zawiera tekst skopiowany z komórki w arkuszu Google Sheets. Pola "Description" i "Last Updated" odświeżają się o zadany czas.
![Discord_rHu9yfV64W](https://user-images.githubusercontent.com/117805804/215160542-ec2ce515-dd2f-4499-823a-fa19919794f5.png)

Jeżeli będziesz chciał lepszą optymalizację pól, skrojoną pod waszego discorda, to przydałoby się dodać tam Bota, nawet nawet na jakiś prywatny pokój, żebym mógł odczytać listę członków i ról.

2023-01-27 18:10 UTC, PiotrWeppo commented
> Jak coś to wydaje mi się, że to ten plugin do flake'a wszystko psuje. Po co dodałeś ten plugin?

nie pamiętam, ale był przedstawiony jako rozszerzenie funcjonalności flake8:
https://pypi.org/project/flake8-bugbear/

2023-01-27 18:55 UTC, pktiuk commented
> > Jak coś to wydaje mi się, że to ten plugin do flake'a wszystko psuje. Po co dodałeś ten plugin?
> 
> nie pamiętam, ale był przedstawiony jako rozszerzenie funcjonalności flake8: https://pypi.org/project/flake8-bugbear/

Ja bym spróbował go usunąć i zobaczył, czy wtedy CI zacznie działać.